habitat-sh/foundational-packages

linux/bootstrap/build-tools/host-tools/native-busybox-static/.hab-plan-config.toml
linux/bootstrap/build-tools/host-tools/native-busybox-static/plan.sh
linux/bootstrap/build-tools/host-tools/native-file/.hab-plan-config.toml
linux/bootstrap/build-tools/host-tools/native-file/plan.sh
linux/bootstrap/build-tools/host-tools/native-gmp/.hab-plan-config.toml
linux/bootstrap/build-tools/host-tools/native-gmp/plan.sh
linux/bootstrap/build-tools/host-tools/native-isl/.hab-plan-config.toml
linux/bootstrap/build-tools/host-tools/native-isl/plan.sh
linux/bootstrap/build-tools/host-tools/native-libmpc/.hab-plan-config.toml
linux/bootstrap/build-tools/host-tools/native-libmpc/plan.sh
linux/bootstrap/build-tools/host-tools/native-mpfr/.hab-plan-config.toml
linux/bootstrap/build-tools/host-tools/native-mpfr/plan.sh
linux/bootstrap/build-tools/host-tools/native-patchelf/.hab-plan-config.toml
linux/bootstrap/build-tools/host-tools/native-patchelf/plan.sh
linux/bootstrap/build-tools/host-tools/native-rust/x86_64-linux/.hab-plan-config.toml
linux/bootstrap/build-tools/host-tools/native-rust/x86_64-linux/plan.sh

add host tools

---

windows/applications/version-management/git/plan.ps1
windows/applications/virtualization/docker/plan.ps1
windows/data/cacerts/plan.ps1
windows/development/compilers/rust/plan.ps1
windows/development/interpreters/node/plan.ps1
windows/development/libraries/libsodium/plan.ps1
windows/development/libraries/protobuf/plan.ps1
windows/development/libraries/zeromq/plan.ps1
windows/development/libraries/zlib/plan.ps1
windows/development/sdk/11/plan.ps1
windows/development/tools/misc/lessmsi/plan.ps1
windows/development/tools/misc/wix/plan.ps1
windows/shells/powershell/plan.ps1
windows/tools/admin/visual-build-tools-2022/plan.ps1
windows/tools/admin/visual-cpp-redist-2022/plan.ps1
windows/tools/archivers/7zip/plan.ps1
windows/tools/text/raml2html/plan.ps1

add windows packages

---

windows/development/compilers/rust/plan.ps1

Bumping windows rust package to 1.85.0.

Bumping windows rust to 1.85.0

---

linux/development/compilers/rust/glibc/.hab-plan-config.toml
linux/development/compilers/rust/glibc/plan.sh
linux/tools/networking/curl/plan.sh

Bumping curl to 8.12.1 and rust to 1.85.0.

Bumping curl and rust to latest versions

---

linux/development/libraries/expat/.hab-plan-config.toml
linux/development/libraries/expat/plan.sh

[expat] upgraded to v2.7.1

---

linux/bootstrap/build-tools/cross-tools/build-tools-openssl/.hab-plan-config.toml
linux/bootstrap/stage1/openssl/.hab-plan-config.toml
linux/bootstrap/stage1/openssl/hab-ssl-cert-file.patch
linux/bootstrap/stage1/openssl/plan.sh
linux/development/libraries/openssl/README.md
linux/development/libraries/openssl/glibc/cacert-path.patch
linux/development/libraries/openssl/glibc/plan.sh

https://progresssoftware.atlassian.net/browse/CHEF-20553

openssl plans bumped to 3.2.4 [CHEF-20553]

---

linux/development/libraries/gmp/.hab-plan-config.toml
linux/development/libraries/gmp/plan.sh

[gmp] upgraded to v6.3.0

---

linux/development/libraries/acl/.hab-plan-config.toml
linux/development/libraries/acl/plan.sh

[acl] upgraded to v2.3.2

---

linux/development/interpreters/tcl/.hab-plan-config.toml
linux/development/interpreters/tcl/plan.sh

[tcl] upgraded to v8.6.16

---

linux/development/libraries/libxcrypt/.hab-plan-config.toml
linux/development/libraries/libxcrypt/plan.sh

add libxcrypt v4.4.38

---

linux/tools/misc/less/.hab-plan-config.toml
linux/tools/misc/less/plan.sh

https://progresssoftware.atlassian.net/browse/CHEF-22419

core/less bumped with 668 [CHEF-22419]

---

linux/os-specific/shadow/.hab-plan-config.toml
linux/os-specific/shadow/plan.sh

[shadow] upgraded to v4.17.4

---

linux/development/tools/misc/libtool/.hab-plan-config.toml
linux/development/tools/misc/libtool/plan.sh

[libtool] upgraded to v2.5.4

---

linux/shells/bash/shared/.hab-plan-config.toml
linux/shells/bash/shared/plan.sh
linux/shells/bash/static/.hab-plan-config.toml
linux/shells/bash/static/plan.sh

[bash] upgraded to v5.2.37

---

linux/tools/misc/expect/expect-5.45.4-gcc14-1.patch
linux/tools/misc/expect/plan.sh

[expect] fix for incompactibility with gcc v14.x

---

linux/applications/editors/vim/.hab-plan-config.toml
linux/applications/editors/vim/plan.sh

CHEF-22518 upgrade vim to v9.1.1166

CHEF-22518 upgrade vim to v9.1.1166

---

linux/development/libraries/ncurses/plan.sh

CHEF-22407 upgrade ncurses to v6.5

CHEF-22407 upgrade ncurses to v6.5

---

linux/applications/databases/sqlite/.hab-plan-config.toml
linux/applications/databases/sqlite/plan.sh

CHEF-22592 upgrade sqlite to v3.50.0

CHEF-22592 upgrade sqlite to v3.50.0

---

linux/tools/text/diffutils/.hab-plan-config.toml
linux/tools/text/diffutils/plan.sh

[diffutils] upgraded to v3.11

---

linux/os-specific/procps-ng/.hab-plan-config.toml
linux/os-specific/procps-ng/plan.sh

[procps-ng] upgraded to v4.0.5

---

linux/tools/misc/findutils/.hab-plan-config.toml
linux/tools/misc/findutils/plan.sh

[findutils] upgraded to v4.10.0

---

linux/tools/filesystems/e2fsprogs/.hab-plan-config.toml
linux/tools/filesystems/e2fsprogs/plan.sh

CHEF-22650 upgrade e2fsprogs to 1.47.2

CHEF-22650 upgrade e2fsprogs to 1.47.2

---

linux/data/tzdata/.hab-plan-config.toml
linux/data/tzdata/plan.sh

CHEF-22611 upgrade tzdata to 2025b

CHEF-22611 upgrade tzdata to 2025b

---

linux/data/iana-etc/.hab-plan-config.toml
linux/data/iana-etc/plan.sh

CHEF-22609 upgrade iana-etc to 20250123

CHEF-22609 upgrade iana-etc to 20250123

---

linux/data/cacerts/.hab-plan-config.toml
linux/data/cacerts/plan.sh

CHEF-22607 upgrade cacerts to 2025-05-20

CHEF-22607 upgrade cacerts to 2025-05-20

---

linux/applications/version-management/git/.hab-plan-config.toml
linux/applications/version-management/git/plan.sh

CHEF-22598 upgrade git to 2.49.0

CHEF-22598 upgrade git to 2.49.0

---

linux/development/libraries/nghttp2/.hab-plan-config.toml
linux/development/libraries/nghttp2/plan.sh

CHEF-22591 upgrade nghttp2 to 1.65.0

CHEF-22591 upgrade nghttp2 to 1.65.0

---

linux/applications/editors/mg/.hab-plan-config.toml
linux/applications/editors/mg/plan.sh

CHEF-22599 upgrade mg 20250523

CHEF-22599 upgrade mg 20250523

---

linux/development/libraries/libarchive/.hab-plan-config.toml
linux/development/libraries/libarchive/plan.sh

CHEF-22662 upgrade libarchive to 3.8.1

CHEF-22662 upgrade libarchive to 3.8.1

---

linux/tools/misc/parallel/.hab-plan-config.toml
linux/tools/misc/parallel/plan.sh

CHEF-22652 upgrade parallel to 20250522

CHEF-22652 upgrade parallel to 20250522

---

linux/development/tools/misc/texinfo/.hab-plan-config.toml
linux/development/tools/misc/texinfo/plan.sh

CHEF-22661 upgrade texinfo to 7.2

CHEF-22661 upgrade texinfo to 7.2

---

linux/tools/networking/wget/shared/.hab-plan-config.toml
linux/tools/networking/wget/shared/plan.sh

CHEF-22654 upgrade wget to 1.25.0

CHEF-22654 upgrade wget to 1.25.0

---

linux/development/libraries/libxml2/.hab-plan-config.toml
linux/development/libraries/libxml2/plan.sh

CHEF-22666 upgrade libxml2 to 2.14.3

CHEF-22666 upgrade libxml2 to 2.14.3

---

linux/tools/compression/xz/.hab-plan-config.toml
linux/tools/compression/xz/plan.sh

[xz] fix for CVE-2025-31115

---

linux/development/interpreters/perl/.hab-plan-config.toml
linux/development/interpreters/perl/plan.sh

CHEF-22420 upgrade perl to v5.40.1

CHEF-22420 upgrade perl to v5.40.1

---

linux/tools/compression/lz4/.hab-plan-config.toml
linux/tools/compression/lz4/plan.sh

[lz4] upgraded to v1.10.0

---

linux/tools/compression/gzip/.hab-plan-config.toml
linux/tools/compression/gzip/plan.sh

https://progresssoftware.atlassian.net/browse/CHEF-22887

gzip bumped to 1.14 [CHEF-22887]

---

linux/tools/networking/curl/plan.sh

[curl] fix for CVE-2025-5399

---

linux/tools/archivers/tar/plan.sh

[tar] added license files to package

---

linux/tools/archivers/unzip/plan.sh

[unzip] added license files to package

---

linux/os-specific/util-linux/plan.sh

[util-linux] added license files to package

---

linux/os-specific/shadow/plan.sh

[shadow] added license files to package

---

linux/os-specific/procps-ng/plan.sh

[procps-ng] added license files to package

---

linux/os-specific/busybox/static/plan.sh

[busybox-static] added license files to package

---

linux/applications/databases/sqlite/plan.sh

[sqlite] added license files to package

---

linux/applications/editors/vim/plan.sh

[vim] added license files to package

---

linux/applications/version-management/git/plan.sh

[git] added license files to package

---

linux/tools/filesystems/e2fsprogs/plan.sh

[e2fsprogs] added license files to package

---

linux/tools/compression/bzip2/plan.sh

[bzip2] added license files to package

---

linux/tools/compression/gzip/plan.sh

[gzip] added license files to package

---

linux/tools/compression/lz4/plan.sh

[lz4] added license files to package

---

linux/tools/compression/lzip/plan.sh

[lzip] added license files to package

---

linux/tools/compression/lzop/plan.sh

[lzop] added license files to package

---

linux/tools/misc/expect/plan.sh

[expect] added license files to package

---

linux/tools/misc/file/plan.sh

[file] added license files to package

---

linux/tools/misc/findutils/plan.sh

[findutils] added license files to package

---

linux/tools/networking/wget/shared/plan.sh

[wget] added license files to package

---

linux/tools/networking/curl/plan.sh

[curl] added license files to package

---

linux/tools/networking/openssh/plan.sh

[openssh] added license files to package

---

linux/tools/misc/parallel/plan.sh

[parallel] added license files to package

---

linux/tools/text/diffutils/plan.sh

[diffutils] added license files to package

---

linux/tools/text/gawk/plan.sh

[gawk] added license files to package

---

linux/tools/text/patch/plan.sh

[patch] added license files to package

---

linux/tools/text/grep/plan.sh

[grep] added license files to package

---

windows/development/interpreters/node/plan.ps1

[node] upgraded to v22.16.0

---

windows/tools/archivers/7zip/plan.ps1

https://progresssoftware.atlassian.net/browse/CHEF-23270

7zip bumped to 24.09 for windows [CHEF-23270]

---

windows/tools/admin/visual-build-tools-2022/plan.ps1

CHEF-23267 upgrade VS buildtools to 17.4.7

CHEF-23267 upgrade VS buildtools to 17.4.7

---

windows/tools/admin/visual-build-tools-2022/plan.ps1

typo in folder path

---

linux/development/interpreters/node/x86_64-linux/.hab-plan-config.toml
linux/development/interpreters/node/x86_64-linux/plan.sh

[node] upgraded to v22.17.0
